//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fruitkha_main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adslogo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string avatar { get; set; }
        public Nullable<int> ads_supplier { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
