//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fruitkha_main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int id { get; set; }
        public string avatar { get; set; }
        public string title { get; set; }
        public Nullable<int> category_id { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> create_day { get; set; }
        public string articles_content { get; set; }
    
        public virtual category category { get; set; }
    }
}
