//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fruitkha_main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> us_id { get; set; }
        public Nullable<int> prd_id { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> old_price { get; set; }
        public Nullable<int> sale { get; set; }
        public string qty { get; set; }
        public string avatar { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
